// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBi_VcIUf12gT6eHk2o3R1lbdfwflrzcLI',
    appId: '1:469930598106:web:0c5f02aa7e7ab9359c0fe3',
    messagingSenderId: '469930598106',
    projectId: 'bachatbot-98145',
    authDomain: 'bachatbot-98145.firebaseapp.com',
    databaseURL:
        'https://bachatbot-98145-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'bachatbot-98145.firebasestorage.app',
    measurementId: 'G-XBDCJPDS6S',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCGuze8izfXmsudu6rpwS5sj3q3kiuxKNE',
    appId: '1:469930598106:android:3cdd922240ceac3c9c0fe3',
    messagingSenderId: '469930598106',
    projectId: 'bachatbot-98145',
    databaseURL:
        'https://bachatbot-98145-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'bachatbot-98145.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC4r2PCLpyi0G7ExqRXih6ZddaX410_qr4',
    appId: '1:469930598106:ios:3426c4874f0d61339c0fe3',
    messagingSenderId: '469930598106',
    projectId: 'bachatbot-98145',
    databaseURL:
        'https://bachatbot-98145-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'bachatbot-98145.firebasestorage.app',
    iosBundleId: 'com.bachatbot.bachatbot',
  );
}
